services:
  book_catalog:
    image: book_catalog:4
    build:
      context: ./bookcatalog 
      dockerfile: Dockerfile
    container_name: book_catalog
    platform: "linux/amd64" 
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://tharuka_sit722_part3_user:kujg7KYIxL90r3TzLHO9P6reOIMu1mDf@dpg-crmqmb08fa8c73anclq0-a.oregon-postgres.render.com/tharuka_sit722_part3
    restart: "no"

  inventory_management:
    image: inventory management:4
    bulld:
      context: ./inventory_management
      dockerfiles: Dockerfile
  container_name: inventory_management
  platform: Linux/and64
  ports:
    - "8000:8000" 
  environment:
    -DATABASE_URL=postgresql://tharuka_sit722_part3_user:kujg7KYIxL90r3TzLHO9P6reOIMu1mDf@dpg-crmqmb08fa8c73anclq0-a.oregon-postgres.render.com/tharuka_sit722_part3
  restart: "no"