apiVersion: apps/v1
kind: Deployment 
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: book-catalog
        image: sit722week8tharuka.azurecr.io/book_catalog:4
        ports:
        - containerPort: 8000 
        env:
        - name: DATABASE_URL
          value: "postgresql://tharuka_sit722_part3_user:kujg7KYIxL90r3TzLHO9P6reOIMu1mDf@dpg-crmqmb08fa8c73anclq0-a.oregon-postgres.render.com/tharuka_sit722_part3"
          
---
apiVersion: v1
kind: Service 
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000


---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: inventory-management
        image: sit722week8tharuka.azurecr.io/inventory_management:4
        ports:
        - containerPort: 8000 
        env:
        - name: DATABASE_URL
          value: "postgresql://tharuka_sit722_part3_user:kujg7KYIxL90r3TzLHO9P6reOIMu1mDf@dpg-crmqmb08fa8c73anclq0-a.oregon-postgres.render.com/tharuka_sit722_part3"
          
---
apiVersion: v1
kind: Service 
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  